repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: cpp-format
        name: C++ formatting
        description: Runs format_cpp.sh
        entry: scripts/format_cpp.sh
        args: [format]
        language: script
