task:
  data_collection_time: 8
  policy_execution_time: 20
  joint_pos_init: [0.0098,  0.3146,  0.0178, -1.9033, -0.0331,  2.2675, -0.5955]
  module: 
    _target_: task_modules.circle.CircleTask

model:
  lr: 1e-5
  epochs: 100
  batchsize: 100
  n_in: 1
  n_hiddens: [100, 50]
  n_out: 7
  filename: "model.pt"
